spring.application.name=identity
api.version=v1
server.port=5000
api.current.url=http://localhost:{server.port}/api

swagger.base-path=/**
springdoc.swagger-ui.path=/api/docs
springdoc.swagger-ui.doc-expansion=none
springdoc.api.version=${api.version}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB