# Generated by Django 5.2.7 on 2025-11-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW', 'View'), ('OTHER', 'Other')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('entity_name', models.CharField(max_length=100)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('action_timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
    ]
