
from enum import Enum

class Events(Enum):
    USER_CREATED = "USER_CREATED"
    CLAIM_ADDED = "CLAIM_ADDED"
    CLAIM_REMOVED = "CLAIM_REMOVED"
    ROLE_ADDED_TO_USER = "ROLE_ADDED_TO_USER"
    ROLE_REMOVED_FROM_USER = "ROLE_REMOVED_FROM_USER"

    PAYMENT_COMPLETED = "PAYMENT_COMPLETED"
    PAYMENT_FAILED = "PAYMENT_FAILED"

    LISTING_CREATED = "LISTING_CREATED"
    LISTING_DELETED = "LISTING_DELETED"
    LISTING_DEACTIVATED = "LISTING_DEACTIVATED"
    LISTING_ACTIVATED = "LISTING_ACTIVATED"
