
from enum import Enum

class Events(Enum):
    BOOKING_CONFIRMED = "BOOKING_CONFIRMED"
    PAYMENT_COMPLETED = "PAYMENT_COMPLETED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    RECEIPT_GENERATED = "RECEIPT_GENERATED"
